import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface AppealData {
  id: string;
  address: string;
  owner: string;
  issue: string;
  assessedValue: number;
  comparables: {
    address: string;
    value: number;
    diff: number;
  }[];
}

export const generateDefensePacket = (data: AppealData) => {
  const doc = new jsPDF();
  const primaryColor = [0, 255, 255]; // Cyan
  const secondaryColor = [15, 23, 42]; // Slate 900

  // Header
  doc.setFillColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('TERRAFUSION', 14, 20);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('SOVEREIGN VALUATION ORGANISM', 14, 28);
  doc.text('LEGAL DEFENSE PACKET', 14, 34);

  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.setFontSize(12);
  doc.text(`CASE ID: ${data.id}`, 150, 20);
  doc.text(`DATE: ${new Date().toLocaleDateString()}`, 150, 28);

  // Subject Property
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('SUBJECT PROPERTY', 14, 55);

  autoTable(doc, {
    startY: 60,
    head: [['Attribute', 'Details']],
    body: [
      ['Address', data.address],
      ['Owner', data.owner],
      ['Appeal Issue', data.issue],
      ['Assessed Value', `$${data.assessedValue.toLocaleString()}`],
    ],
    theme: 'grid',
    headStyles: { fillColor: secondaryColor as any, textColor: [255, 255, 255] },
    styles: { fontSize: 10 },
  });

  // Analysis
  const finalY = (doc as any).lastAutoTable.finalY || 100;
  doc.setFontSize(14);
  doc.text('AI EQUITY ANALYSIS', 14, finalY + 15);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const analysisText = `The TerraFusion Quantum Core has analyzed ${data.comparables.length} comparable properties in the immediate vicinity. The subject property's assessment is consistent with market evidence and falls within the acceptable range of deviation.`;
  doc.text(analysisText, 14, finalY + 25, { maxWidth: 180 });

  // Comparables Table
  autoTable(doc, {
    startY: finalY + 40,
    head: [['Comparable Address', 'Value / Unit', 'Deviation']],
    body: data.comparables.map(comp => [
      comp.address,
      `$${comp.value.toLocaleString()}`,
      `${comp.diff > 0 ? '+' : ''}${comp.diff}%`
    ]),
    theme: 'striped',
    headStyles: { fillColor: secondaryColor as any },
    alternateRowStyles: { fillColor: [240, 240, 240] },
  });

  // Conclusion
  const conclusionY = (doc as any).lastAutoTable.finalY + 20;
  doc.setFillColor(240, 255, 255);
  doc.rect(14, conclusionY, 182, 30, 'F');
  doc.setDrawColor(0, 255, 255);
  doc.rect(14, conclusionY, 182, 30, 'S');

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('RECOMMENDATION: DENY APPEAL', 20, conclusionY + 12);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Evidence supports the current assessed value. No adjustment warranted.', 20, conclusionY + 20);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by TerraFusion Legal Defense Agent v4.1', 14, 280);
  doc.text('CONFIDENTIAL - FOR OFFICIAL USE ONLY', 140, 280);

  doc.save(`Defense_Packet_${data.id}.pdf`);
};
