/**
 * Calibration Snapshot Export Endpoints
 * Provides GET /api/calibration/:id/export.csv and /api/calibration/:id/export.pdf
 * Both endpoints authenticate via session cookie and stream the file to the client.
 */

import type { Request, Response } from "express";
import { getDb } from "./db";
import { calibrationSnapshots } from "../drizzle/schema";
import { and, eq } from "drizzle-orm";
import { sdk } from "./_core/sdk";

// ─── Auth helper ──────────────────────────────────────────────────────────────

async function authenticateExportRequest(req: Request): Promise<{ id: number; openId: string } | null> {
  try {
    const user = await sdk.authenticateRequest(req);
    return user ? { id: user.id, openId: user.openId } : null;
  } catch {
    return null;
  }
}

// ─── Fetch snapshot helper ────────────────────────────────────────────────────

async function fetchSnapshot(snapshotId: number, userId: number) {
  const db = await getDb();
  if (!db) return null;
  const [snapshot] = await db
    .select()
    .from(calibrationSnapshots)
    .where(
      and(
        eq(calibrationSnapshots.id, snapshotId),
        eq(calibrationSnapshots.userId, userId)
      )
    )
    .limit(1);
  return snapshot ?? null;
}

// ─── Fetch all snapshots for a county (for full history export) ───────────────

async function fetchAllSnapshots(userId: number, countyName?: string) {
  const db = await getDb();
  if (!db) return [];
  const conditions = [eq(calibrationSnapshots.userId, userId)];
  if (countyName) conditions.push(eq(calibrationSnapshots.countyName, countyName));
  return db
    .select()
    .from(calibrationSnapshots)
    .where(and(...conditions))
    .orderBy(calibrationSnapshots.createdAt);
}

// ─── CSV export ───────────────────────────────────────────────────────────────

function buildCsvForSnapshot(snapshot: NonNullable<Awaited<ReturnType<typeof fetchSnapshot>>>): string {
  let costRates: Record<string, number> = {};
  try { costRates = JSON.parse(snapshot.costRates as string); } catch { /* empty */ }

  const lines: string[] = [];

  // Header block
  lines.push(`TerraFusion Mass Valuation Appraisal Suite`);
  lines.push(`Calibration Snapshot Export`);
  lines.push(``);
  lines.push(`Snapshot Name,${escCsv(snapshot.name)}`);
  lines.push(`Version ID,${snapshot.id}`);
  lines.push(`County,${escCsv(snapshot.countyName ?? "N/A")}`);
  lines.push(`Export Date,${new Date().toISOString()}`);
  lines.push(`Snapshot Date,${new Date(snapshot.createdAt).toISOString()}`);
  lines.push(`Status,${snapshot.isActive ? "Active" : "Archived"}`);
  if (snapshot.description) {
    lines.push(`Description,${escCsv(snapshot.description)}`);
  }
  lines.push(``);

  // IAAO Metrics
  lines.push(`IAAO Performance Metrics`);
  lines.push(`Metric,Value,Target Range,Status`);
  const ratio = snapshot.snapshotMedianRatio;
  const cod = snapshot.snapshotCod;
  const prd = snapshot.snapshotPrd;
  lines.push(`Median Sales Ratio,${ratio != null ? ratio.toFixed(4) : "N/A"},0.90 – 1.10,${ratio != null ? (ratio >= 0.9 && ratio <= 1.1 ? "PASS" : "FAIL") : "N/A"}`);
  lines.push(`COD (Coefficient of Dispersion),${cod != null ? cod.toFixed(4) : "N/A"},< 10%,${cod != null ? (cod < 10 ? "PASS" : "FAIL") : "N/A"}`);
  lines.push(`PRD (Price-Related Differential),${prd != null ? prd.toFixed(4) : "N/A"},0.98 – 1.03,${prd != null ? (prd >= 0.98 && prd <= 1.03 ? "PASS" : "FAIL") : "N/A"}`);
  lines.push(``);

  // Cost Rates
  lines.push(`Cost Rate Table`);
  lines.push(`Property Class,Rate ($/sqft),IAAO Baseline ($/sqft),Delta,% Change`);
  const IAAO_BASELINE: Record<string, number> = {
    "Residential (Wood Frame)": 142,
    "Residential (Masonry)": 168,
    "Commercial (Office)": 195,
    "Commercial (Retail)": 178,
    "Industrial (Light)": 112,
    "Industrial (Heavy)": 138,
  };
  for (const [cls, rate] of Object.entries(costRates)) {
    const baseline = IAAO_BASELINE[cls] ?? null;
    const delta = baseline != null ? (rate - baseline).toFixed(2) : "N/A";
    const pct = baseline != null && baseline !== 0 ? (((rate - baseline) / baseline) * 100).toFixed(2) + "%" : "N/A";
    lines.push(`${escCsv(cls)},${rate},${baseline ?? "N/A"},${delta},${pct}`);
  }
  lines.push(``);
  lines.push(`Generated by TerraFusion v2.0 — For regulatory submission use only.`);

  return lines.join("\r\n");
}

function buildCsvForHistory(
  snapshots: Awaited<ReturnType<typeof fetchAllSnapshots>>,
  countyName?: string
): string {
  const lines: string[] = [];
  lines.push(`TerraFusion Mass Valuation Appraisal Suite`);
  lines.push(`Calibration Version History Export`);
  lines.push(``);
  lines.push(`County,${escCsv(countyName ?? "All Counties")}`);
  lines.push(`Export Date,${new Date().toISOString()}`);
  lines.push(`Total Snapshots,${snapshots.length}`);
  lines.push(``);

  lines.push(`Version,Name,County,Date,Status,Median Ratio,COD,PRD,Description`);
  for (const s of snapshots) {
    lines.push([
      s.id,
      escCsv(s.name),
      escCsv(s.countyName ?? ""),
      new Date(s.createdAt).toISOString(),
      s.isActive ? "Active" : "Archived",
      s.snapshotMedianRatio?.toFixed(4) ?? "",
      s.snapshotCod?.toFixed(4) ?? "",
      s.snapshotPrd?.toFixed(4) ?? "",
      escCsv(s.description ?? ""),
    ].join(","));
  }
  lines.push(``);
  lines.push(`Generated by TerraFusion v2.0 — For regulatory submission use only.`);
  return lines.join("\r\n");
}

function escCsv(val: string): string {
  if (/[",\r\n]/.test(val)) return `"${val.replace(/"/g, '""')}"`;
  return val;
}

// ─── PDF export ───────────────────────────────────────────────────────────────

async function buildPdfForSnapshot(
  snapshot: NonNullable<Awaited<ReturnType<typeof fetchSnapshot>>>
): Promise<Buffer> {
  // Dynamic imports to avoid ESM/CJS issues at module load time
  const { jsPDF } = await import("jspdf");
  const autoTableModule = await import("jspdf-autotable");
  const autoTable: (doc: InstanceType<typeof jsPDF>, options: object) => void =
    (autoTableModule as any).default ?? (autoTableModule as any);

  let costRates: Record<string, number> = {};
  try { costRates = JSON.parse(snapshot.costRates as string); } catch { /* empty */ }

  const IAAO_BASELINE: Record<string, number> = {
    "Residential (Wood Frame)": 142,
    "Residential (Masonry)": 168,
    "Commercial (Office)": 195,
    "Commercial (Retail)": 178,
    "Industrial (Light)": 112,
    "Industrial (Heavy)": 138,
  };

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 18;
  const contentW = pageW - margin * 2;

  // ── Cover header ──
  doc.setFillColor(11, 16, 32); // #0b1020
  doc.rect(0, 0, pageW, 42, "F");

  doc.setTextColor(0, 255, 238); // #00ffee
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("TerraFusion", margin, 16);

  doc.setTextColor(200, 210, 230);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Mass Valuation Appraisal Suite", margin, 23);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Calibration Snapshot Report", margin, 35);

  // ── Metadata block ──
  let y = 54;
  const metaRows: [string, string][] = [
    ["Snapshot Name", snapshot.name],
    ["Version ID", String(snapshot.id)],
    ["County", snapshot.countyName ?? "N/A"],
    ["Status", snapshot.isActive ? "Active" : "Archived"],
    ["Snapshot Date", new Date(snapshot.createdAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })],
    ["Export Date", new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })],
  ];
  if (snapshot.description) {
    metaRows.push(["Description", snapshot.description]);
  }

  autoTable(doc, {
    startY: y,
    head: [],
    body: metaRows,
    theme: "plain",
    styles: { fontSize: 10, cellPadding: 2.5 },
    columnStyles: {
      0: { fontStyle: "bold", textColor: [80, 100, 130], cellWidth: 48 },
      1: { textColor: [20, 30, 50] },
    },
    margin: { left: margin, right: margin },
  });

  y = (doc as any).lastAutoTable.finalY + 10;

  // ── IAAO Metrics section ──
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(11, 16, 32);
  doc.text("IAAO Performance Metrics", margin, y);
  y += 6;

  const ratio = snapshot.snapshotMedianRatio;
  const cod = snapshot.snapshotCod;
  const prd = snapshot.snapshotPrd;

  const metricsBody = [
    [
      "Median Sales Ratio",
      ratio != null ? ratio.toFixed(4) : "N/A",
      "0.90 – 1.10",
      ratio != null ? (ratio >= 0.9 && ratio <= 1.1 ? "PASS" : "FAIL") : "N/A",
    ],
    [
      "COD (Coefficient of Dispersion)",
      cod != null ? cod.toFixed(4) : "N/A",
      "< 10%",
      cod != null ? (cod < 10 ? "PASS" : "FAIL") : "N/A",
    ],
    [
      "PRD (Price-Related Differential)",
      prd != null ? prd.toFixed(4) : "N/A",
      "0.98 – 1.03",
      prd != null ? (prd >= 0.98 && prd <= 1.03 ? "PASS" : "FAIL") : "N/A",
    ],
  ];

  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value", "Target Range", "Status"]],
    body: metricsBody,
    theme: "striped",
    headStyles: { fillColor: [11, 16, 32], textColor: [0, 255, 238], fontStyle: "bold", fontSize: 9 },
    bodyStyles: { fontSize: 9, textColor: [20, 30, 50] },
    columnStyles: {
      3: {
        fontStyle: "bold",
        // Color will be applied via didDrawCell below
      },
    },
    didDrawCell: (data: any) => {
      if (data.column.index === 3 && data.section === "body") {
        const val = data.cell.text[0];
        if (val === "PASS") {
          doc.setTextColor(22, 163, 74); // green
        } else if (val === "FAIL") {
          doc.setTextColor(220, 38, 38); // red
        } else {
          doc.setTextColor(100, 116, 139); // slate
        }
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.text(val, data.cell.x + data.cell.width / 2, data.cell.y + data.cell.height / 2 + 1, { align: "center" });
      }
    },
    margin: { left: margin, right: margin },
  });

  y = (doc as any).lastAutoTable.finalY + 10;

  // ── Cost Rate Table ──
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(11, 16, 32);
  doc.text("Cost Rate Table", margin, y);
  y += 6;

  const costBody = Object.entries(costRates).map(([cls, rate]) => {
    const baseline = IAAO_BASELINE[cls] ?? null;
    const delta = baseline != null ? (rate - baseline) : null;
    const pct = baseline != null && baseline !== 0 ? ((rate - baseline) / baseline) * 100 : null;
    return [
      cls,
      `$${rate}/sqft`,
      baseline != null ? `$${baseline}/sqft` : "N/A",
      delta != null ? `${delta >= 0 ? "+" : ""}${delta.toFixed(2)}` : "N/A",
      pct != null ? `${pct >= 0 ? "+" : ""}${pct.toFixed(1)}%` : "N/A",
    ];
  });

  autoTable(doc, {
    startY: y,
    head: [["Property Class", "Rate", "IAAO Baseline", "Delta", "% Change"]],
    body: costBody,
    theme: "striped",
    headStyles: { fillColor: [11, 16, 32], textColor: [0, 255, 238], fontStyle: "bold", fontSize: 9 },
    bodyStyles: { fontSize: 9, textColor: [20, 30, 50] },
    columnStyles: {
      1: { fontStyle: "bold" },
      3: { halign: "right" },
      4: { halign: "right" },
    },
    margin: { left: margin, right: margin },
  });

  y = (doc as any).lastAutoTable.finalY + 14;

  // ── Footer ──
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(150, 160, 180);
  const footerText = `Generated by TerraFusion v2.0 on ${new Date().toISOString()} — For regulatory submission use only. This document is confidential.`;
  const footerLines = doc.splitTextToSize(footerText, contentW);
  doc.text(footerLines, margin, y);

  // Page numbers
  const pageCount = (doc.internal as any).getNumberOfPages?.() ?? 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 160, 180);
    doc.text(`Page ${i} of ${pageCount}`, pageW - margin, doc.internal.pageSize.getHeight() - 8, { align: "right" });
  }

  return Buffer.from(doc.output("arraybuffer"));
}

async function buildPdfForHistory(
  snapshots: Awaited<ReturnType<typeof fetchAllSnapshots>>,
  countyName?: string
): Promise<Buffer> {
  const { jsPDF } = await import("jspdf");
  const autoTableModule = await import("jspdf-autotable");
  const autoTable: (doc: InstanceType<typeof jsPDF>, options: object) => void =
    (autoTableModule as any).default ?? (autoTableModule as any);

  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 18;

  // Header
  doc.setFillColor(11, 16, 32);
  doc.rect(0, 0, pageW, 36, "F");
  doc.setTextColor(0, 255, 238);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("TerraFusion — Calibration Version History", margin, 16);
  doc.setTextColor(200, 210, 230);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`County: ${countyName ?? "All Counties"} · Exported: ${new Date().toLocaleDateString()} · ${snapshots.length} snapshots`, margin, 27);

  const body = snapshots.map((s, i) => {
    let rateCount = 0;
    try { rateCount = Object.keys(JSON.parse(s.costRates as string)).length; } catch { /* empty */ }
    return [
      String(snapshots.length - i),
      s.name,
      s.countyName ?? "",
      new Date(s.createdAt).toLocaleDateString(),
      s.isActive ? "Active" : "Archived",
      s.snapshotMedianRatio?.toFixed(3) ?? "—",
      s.snapshotCod?.toFixed(3) ?? "—",
      s.snapshotPrd?.toFixed(3) ?? "—",
      String(rateCount),
      s.description ? s.description.slice(0, 60) + (s.description.length > 60 ? "…" : "") : "",
    ];
  });

  autoTable(doc, {
    startY: 44,
    head: [["#", "Name", "County", "Date", "Status", "Ratio", "COD", "PRD", "Rates", "Description"]],
    body,
    theme: "striped",
    headStyles: { fillColor: [11, 16, 32], textColor: [0, 255, 238], fontStyle: "bold", fontSize: 8 },
    bodyStyles: { fontSize: 8, textColor: [20, 30, 50] },
    columnStyles: {
      0: { cellWidth: 10, halign: "center" },
      4: { fontStyle: "bold" },
      5: { halign: "right" },
      6: { halign: "right" },
      7: { halign: "right" },
      8: { halign: "center" },
    },
    margin: { left: margin, right: margin },
  });

  const pageCount = (doc.internal as any).getNumberOfPages?.() ?? 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150, 160, 180);
    doc.text(`Page ${i} of ${pageCount}`, pageW - margin, doc.internal.pageSize.getHeight() - 6, { align: "right" });
  }

  return Buffer.from(doc.output("arraybuffer"));
}

// ─── Express route handlers ───────────────────────────────────────────────────

/** GET /api/calibration/:id/export.csv — single snapshot CSV */
export async function handleExportSnapshotCsv(req: Request, res: Response) {
  const user = await authenticateExportRequest(req);
  if (!user) return res.status(401).json({ error: "Unauthorized" });

  const id = parseInt(req.params.id, 10);
  if (isNaN(id)) return res.status(400).json({ error: "Invalid snapshot ID" });

  const snapshot = await fetchSnapshot(id, user.id);
  if (!snapshot) return res.status(404).json({ error: "Snapshot not found" });

  const csv = buildCsvForSnapshot(snapshot);
  const filename = `calibration-${snapshot.countyName ?? "snapshot"}-v${id}-${Date.now()}.csv`;
  res.setHeader("Content-Type", "text/csv; charset=utf-8");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
  res.send(csv);
}

/** GET /api/calibration/:id/export.pdf — single snapshot PDF */
export async function handleExportSnapshotPdf(req: Request, res: Response) {
  const user = await authenticateExportRequest(req);
  if (!user) return res.status(401).json({ error: "Unauthorized" });

  const id = parseInt(req.params.id, 10);
  if (isNaN(id)) return res.status(400).json({ error: "Invalid snapshot ID" });

  const snapshot = await fetchSnapshot(id, user.id);
  if (!snapshot) return res.status(404).json({ error: "Snapshot not found" });

  try {
    const pdfBuffer = await buildPdfForSnapshot(snapshot);
    const filename = `calibration-${snapshot.countyName ?? "snapshot"}-v${id}-${Date.now()}.pdf`;
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.send(pdfBuffer);
  } catch (err) {
    console.error("[CalibrationExport] PDF generation error:", err);
    res.status(500).json({ error: "PDF generation failed" });
  }
}

/** GET /api/calibration/history/export.csv?county=King — full history CSV */
export async function handleExportHistoryCsv(req: Request, res: Response) {
  const user = await authenticateExportRequest(req);
  if (!user) return res.status(401).json({ error: "Unauthorized" });

  const county = typeof req.query.county === "string" ? req.query.county : undefined;
  const snapshots = await fetchAllSnapshots(user.id, county);

  const csv = buildCsvForHistory(snapshots, county);
  const filename = `calibration-history-${county ?? "all"}-${Date.now()}.csv`;
  res.setHeader("Content-Type", "text/csv; charset=utf-8");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
  res.send(csv);
}

/** GET /api/calibration/history/export.pdf?county=King — full history PDF */
export async function handleExportHistoryPdf(req: Request, res: Response) {
  const user = await authenticateExportRequest(req);
  if (!user) return res.status(401).json({ error: "Unauthorized" });

  const county = typeof req.query.county === "string" ? req.query.county : undefined;
  const snapshots = await fetchAllSnapshots(user.id, county);

  try {
    const pdfBuffer = await buildPdfForHistory(snapshots, county);
    const filename = `calibration-history-${county ?? "all"}-${Date.now()}.pdf`;
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.send(pdfBuffer);
  } catch (err) {
    console.error("[CalibrationExport] History PDF generation error:", err);
    res.status(500).json({ error: "PDF generation failed" });
  }
}
