/**
 * Cron Job Configuration
 * Automated scheduled tasks for the TerraFusion platform
 */
import { runAppealReminderChecks } from "./appealReminders";
import { notifyOwner } from "./_core/notification";
import { getDb } from "./db";
import { countyStatistics, appeals, parcels, sales } from "../drizzle/schema";
import { count } from "drizzle-orm";

// ─── Monthly Report State ─────────────────────────────────────────────────────
let lastMonthlyReportSentAt: Date | null = null;
let lastMonthlyReportStatus: "success" | "error" | "never" = "never";

export function getMonthlyReportStatus() {
  return {
    lastSentAt: lastMonthlyReportSentAt,
    status: lastMonthlyReportStatus,
  };
}

// ─── Monthly Report Content Generation ───────────────────────────────────────

async function generateMonthlyReportContent(): Promise<string> {
  const db = await getDb();
  const now = new Date();
  const reportMonth = now.toLocaleString("en-US", { month: "long", year: "numeric" });

  let countyRows: (typeof countyStatistics.$inferSelect)[] = [];
  let totalParcels = 0;
  let totalSales = 0;
  let pendingAppeals = 0;
  let resolvedAppeals = 0;
  let hearingScheduled = 0;

  if (db) {
    try {
      countyRows = await db.select().from(countyStatistics).limit(10);
    } catch { /* leave empty */ }

    try {
      const [r] = await db.select({ total: count() }).from(parcels);
      totalParcels = r?.total ?? 0;
    } catch { /* leave 0 */ }

    try {
      const [r] = await db.select({ total: count() }).from(sales);
      totalSales = r?.total ?? 0;
    } catch { /* leave 0 */ }

    try {
      const rows = await db
        .select({ status: appeals.status, cnt: count() })
        .from(appeals)
        .groupBy(appeals.status);
      for (const row of rows) {
        if (row.status === "pending") pendingAppeals = row.cnt;
        else if (row.status === "resolved") resolvedAppeals = row.cnt;
        else if (row.status === "hearing_scheduled") hearingScheduled = row.cnt;
      }
    } catch { /* leave zeros */ }
  }

  const countyLines = countyRows
    .filter((c) => c.medianRatio !== null)
    .map((c) => {
      const ratio = c.medianRatio?.toFixed(3) ?? "N/A";
      const cod = c.cod?.toFixed(1) ?? "N/A";
      const prd = c.prd?.toFixed(3) ?? "N/A";
      const ratioPass = c.medianRatio !== null && c.medianRatio >= 0.9 && c.medianRatio <= 1.1;
      const codPass = c.cod !== null && c.cod < 15;
      const prdPass = c.prd !== null && c.prd >= 0.98 && c.prd <= 1.03;
      const overall = ratioPass && codPass && prdPass ? "COMPLIANT" : "REVIEW NEEDED";
      return `  • ${c.countyName}: Ratio ${ratio} ${ratioPass ? "✓" : "✗"} | COD ${cod}% ${codPass ? "✓" : "✗"} | PRD ${prd} ${prdPass ? "✓" : "✗"} | ${overall}`;
    })
    .join("\n");

  const iaaoSection =
    countyLines.length > 0
      ? `IAAO Ratio Study Compliance by County:\n${countyLines}`
      : "No county ratio study data available this month.";

  return `TerraFusion Monthly Assessment Report — ${reportMonth}
Generated: ${now.toUTCString()}
═══════════════════════════════════════════════════════

PORTFOLIO SUMMARY
─────────────────
  Total Parcels on Roll:   ${totalParcels.toLocaleString()}
  Qualified Sales Records: ${totalSales.toLocaleString()}

APPEALS ACTIVITY
────────────────
  Pending Review:          ${pendingAppeals}
  Hearing Scheduled:       ${hearingScheduled}
  Resolved This Cycle:     ${resolvedAppeals}

${iaaoSection}

IAAO STANDARD REFERENCE RANGES
───────────────────────────────
  Median Ratio (A/S):  0.90 – 1.10  (IAAO Standard on Ratio Studies §4)
  COD (Uniformity):    < 15% residential, < 20% income-producing
  PRD (Vertical Eq.):  0.98 – 1.03  (IAAO Standard on Ratio Studies §6)

─────────────────────────────────────────────────────
This report was automatically generated by TerraFusion.`;
}

// ─── Scheduled Jobs ───────────────────────────────────────────────────────────

/**
 * Schedule: Daily at 9:00 AM
 * Purpose: Check for upcoming hearings and stale appeals
 */
export async function scheduledAppealReminders() {
  console.log("[CronJob] Running scheduled appeal reminder checks at", new Date().toISOString());
  try {
    const results = await runAppealReminderChecks();
    console.log("[CronJob] Appeal reminder checks completed:", results);
    return results;
  } catch (error) {
    console.error("[CronJob] Error in scheduled appeal reminders:", error);
    throw error;
  }
}

/**
 * Schedule: Monthly on 1st at midnight
 * Purpose: Generate and send monthly IAAO statistics report via notifyOwner()
 */
export async function scheduledMonthlyReports() {
  console.log("[CronJob] Running scheduled monthly valuation report at", new Date().toISOString());
  try {
    const content = await generateMonthlyReportContent();
    const now = new Date();
    const reportMonth = now.toLocaleString("en-US", { month: "long", year: "numeric" });

    const sent = await notifyOwner({
      title: `TerraFusion Monthly Report — ${reportMonth}`,
      content,
    });

    lastMonthlyReportSentAt = now;
    lastMonthlyReportStatus = sent ? "success" : "error";

    if (sent) {
      console.log("[CronJob] Monthly valuation report sent successfully.");
    } else {
      console.warn("[CronJob] Monthly report generated but notification delivery failed.");
    }

    return { sent, reportMonth, generatedAt: now.toISOString() };
  } catch (error) {
    lastMonthlyReportStatus = "error";
    console.error("[CronJob] Error in scheduled monthly reports:", error);
    throw error;
  }
}

// ─── Initializer ─────────────────────────────────────────────────────────────

export function initializeCronJobs() {
  console.log("[CronJobs] Initializing cron jobs...");

  // Daily appeal reminders at 9:00 AM
  const nineAmMs = getMillisecondsUntilNextNineAM();
  setTimeout(() => {
    scheduledAppealReminders();
    setInterval(() => scheduledAppealReminders(), 24 * 60 * 60 * 1000);
  }, nineAmMs);
  const nextDailyRun = new Date(Date.now() + nineAmMs);
  console.log(`[CronJob] Appeal reminders scheduled for daily execution at 9:00 AM (next run: ${nextDailyRun.toLocaleString()})`);

  // Monthly reports on 1st of each month at midnight
  const firstOfMonthMs = getMillisecondsUntilFirstOfMonth();
  setTimeout(() => {
    scheduledMonthlyReports();
    setInterval(() => scheduledMonthlyReports(), 30 * 24 * 60 * 60 * 1000);
  }, firstOfMonthMs);
  const nextMonthlyRun = new Date(Date.now() + firstOfMonthMs);
  console.log(`[CronJob] Monthly reports scheduled for 1st of each month at midnight (next run: ${nextMonthlyRun.toLocaleString()})`);

  console.log("[CronJobs] Automated tasks initialized");
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function getMillisecondsUntilNextNineAM(): number {
  const now = new Date();
  const next9AM = new Date();
  next9AM.setHours(9, 0, 0, 0);
  if (now.getHours() >= 9) next9AM.setDate(next9AM.getDate() + 1);
  return next9AM.getTime() - now.getTime();
}

function getMillisecondsUntilFirstOfMonth(): number {
  const now = new Date();
  if (now.getDate() === 1 && now.getHours() === 0 && now.getMinutes() < 5) return 0;
  const first = new Date();
  first.setMonth(first.getMonth() + 1);
  first.setDate(1);
  first.setHours(0, 0, 0, 0);
  return first.getTime() - now.getTime();
}

// ─── Manual Triggers ──────────────────────────────────────────────────────────

export async function triggerAppealRemindersManually() {
  console.log("[CronJob] Manual trigger of appeal reminders");
  return await scheduledAppealReminders();
}

export async function triggerMonthlyReportManually() {
  console.log("[CronJob] Manual trigger of monthly valuation report");
  return await scheduledMonthlyReports();
}
